sudo: false

jobs:
  include:
    - stage: test
      script:
        - shellcheck *.sh
    - stage: deploy
      if: type != pull_request AND branch = master
      script:
        - curl -fs https://raw.githubusercontent.com/lkiesow/automated-quay.io-deployment/master/deploy-on-quay | sh
